Thu, 14 Jun 2018 21:02:41 log.py[line:146] INFO Scrapy 1.5.0 started (bot: PJH)
Thu, 14 Jun 2018 21:02:41 log.py[line:149] INFO Versions: lxml 3.5.0.0, libxml2 2.9.4, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 17.9.0, Python 3.5.2 (default, Nov 23 2017, 16:37:01) - [GCC 5.4.0 20160609], pyOpenSSL 17.5.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Linux-4.13.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
Thu, 14 Jun 2018 21:02:41 crawler.py[line:38] INFO Overridden settings: {'SPIDER_MODULES': ['PJH.spiders'], 'CONCURRENT_REQUESTS': 32, 'BOT_NAME': 'PJH', 'NEWSPIDER_MODULE': 'PJH.spiders', 'ROBOTSTXT_OBEY': True}
Thu, 14 Jun 2018 21:02:41 middleware.py[line:53] INFO Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.memusage.MemoryUsage']
Thu, 14 Jun 2018 21:02:41 middleware.py[line:53] INFO Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'PJH.middlewares.UserAgentMiddleware',
 'PJH.middlewares.CookiesMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
Thu, 14 Jun 2018 21:02:41 middleware.py[line:53] INFO Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
Thu, 14 Jun 2018 21:02:41 middleware.py[line:53] INFO Enabled item pipelines:
[]
Thu, 14 Jun 2018 21:02:41 engine.py[line:256] INFO Spider opened
Thu, 14 Jun 2018 21:02:42 logstats.py[line:48] INFO Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
Thu, 14 Jun 2018 21:02:42 telnet.py[line:60] DEBUG Telnet console listening on 127.0.0.1:6023
Thu, 14 Jun 2018 21:02:42 engine.py[line:133] ERROR Error while obtaining start requests
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/home/nar/Desktop/PJH/PJH/spiders/PJH.py", line 53, in start_requests
    request.meta['source'] = url[1]
IndexError: list index out of range
Thu, 14 Jun 2018 21:02:42 engine.py[line:295] INFO Closing spider (finished)
Thu, 14 Jun 2018 21:02:45 crawler.py[line:258] INFO Received SIG_SETMASK, shutting down gracefully. Send again to force 
Thu, 14 Jun 2018 21:02:46 crawler.py[line:265] INFO Received SIG_SETMASK twice, forcing unclean shutdown
Thu, 14 Jun 2018 21:03:12 signal.py[line:57] ERROR Error caught on signal handler: <function Spider.handle_spider_closed at 0x7fd7c05201e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/nar/Desktop/PJH/PJH/spiders/PJH.py", line 125, in handle_spider_closed
    popularInsert()
  File "/home/nar/Desktop/PJH/PJH/spiders/PJH.py", line 220, in popularInsert
    '$limit': 8
  File "/home/nar/.local/lib/python3.5/site-packages/pymongo/collection.py", line 2179, in aggregate
    with self.__database.client._tmp_session(session, close=False) as s:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/nar/.local/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1407, in _tmp_session
    s = self._ensure_session(session)
  File "/home/nar/.local/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1394, in _ensure_session
    return self.start_session(causal_consistency=False)
  File "/home/nar/.local/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1372, in start_session
    server_session = self._get_server_session()
  File "/home/nar/.local/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1380, in _get_server_session
    return self._topology.get_server_session()
  File "/home/nar/.local/lib/python3.5/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/home/nar/.local/lib/python3.5/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
Thu, 14 Jun 2018 21:03:12 statscollectors.py[line:47] INFO Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 6, 14, 15, 32, 42, 119430),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 2,
 'log_count/INFO': 9,
 'memusage/max': 54366208,
 'memusage/startup': 54366208,
 'start_time': datetime.datetime(2018, 6, 14, 15, 32, 42, 84460)}
Thu, 14 Jun 2018 21:03:12 engine.py[line:326] INFO Spider closed (finished)
